application: kisp0000
version: 1
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on

inbound_services:
- warmup

libraries:
- name: PIL
  version: latest
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0

handlers:
# Endpoints handler
- url: /_ah/spi/.*
  script: kisp_api.APPLICATION

- url: /_ah/queue/deferred
  script: djangoappengine.deferred.handler.application
  login: admin

- url: /_ah/stats/.*
  script: djangoappengine.appstats.application

- url: /media/admin
  static_dir: django/contrib/admin/media
  expiration: '0'

- url: /static
  static_dir: static

- url: /.*
  script: djangoappengine.main.application
